### ISSUE TITLE
How can we use same code or architecture to movie recommendation instead of predicting ratings 

### ISSUE THREAD

**Issue by tiru1930** [jiwidi/Behavior-Sequence-Transformer-Pytorch#1]

**Comment by jiwidi** [comment]
Hi!

How do you want to offer your recommendations? You could use this code to rank your library of movies given a certain user and provide the best rankings as recommendations. If you want to build a model that directly classifies next movie to watch there are also options like https://github.com/jiwidi/Netflix-RNN-Recommender

**Comment by tiru1930** [comment]
Hi 
I am looking for something where i can input user info and product info and want to recommend product purchase behaviour, like which products user wants to buy, how he wants buy and when it is going to, i can use multiple models, as base i thought i could use this
