### ISSUE TITLE
What to use an extra embedding for self.embeddings_user_id and the self.embeddings_movie_id

### ISSUE THREAD

**Issue by shamanez** [jiwidi/Behavior-Sequence-Transformer-Pytorch#5]
Is this for an unknown user or an unknown movie? 

Thanks a lot.

**Comment by jiwidi** [comment]
If you mean why I add the +1 to the size of the embedding table I think it was because the user ids are [1, MAXID] while embedding tables start with index 0 (as is common in programming). Meaning that if you create a embedding table with size 10 it will have indexes 0-9, if you want to use the highest id 10 then you need to create with size+1.

But creating an extra row in the embedding table is also used for unseen values like you mention, is a good practice in recsys.

**Comment by shamanez** [comment]
Thanks. I get it. So the 0th embedding is not get used. Btw what is this         
```
self.embeddings_position  = nn.Embedding(
           sequence_length, int(math.sqrt(len(movies.movie_id.unique())))+1
        )
```

Why do you want to concat this with the movie_history embedding. 

Also I think I found something wrong with the following forward function, 


```
        transfomer_features = self.positional_embedding(transfomer_features)
        transformer_output = self.transfomerlayer(transfomer_features)
        transformer_output = torch.flatten(transformer_output,start_dim=1)

```

please check my comment to the following issue. 
https://github.com/jiwidi/Behavior-Sequence-Transformer-Pytorch/issues/4#issuecomment-1180345557

**Comment by jiwidi** [comment]
> Thanks. I get it. So the 0th embedding is not get used. Btw what is this
> 
> ```
> self.embeddings_position  = nn.Embedding(
>            sequence_length, int(math.sqrt(len(movies.movie_id.unique())))+1
>         )
> ```
> 
> 
> 
> Also I think I found something wrong with the following forward function,
> 
> ```
>         transfomer_features = self.positional_embedding(transfomer_features)
>         transformer_output = self.transfomerlayer(transfomer_features)
>         transformer_output = torch.flatten(transformer_output,start_dim=1)
> ```
> 
> please check my comment to the following issue. [#4 (comment)](https://github.com/jiwidi/Behavior-Sequence-Transformer-Pytorch/issues/4#issuecomment-1180345557)

I'll answer both here:

> Why do you want to concat this with the movie_history embedding.

To create a full item embedding. See how its used in the next comment.

> Also I think I found something wrong with the following forward function,

I think there is nothing wrong the that forward, let me explain how it works and lets see if we are both in the same page:


You have an item 1 with features [2,3,2] (id 2 for feature1, id3 for feature 2, id2 for feature3). The way the paper encodes this item (and recsys in general) is by having embeddings for each feature value as well as an embedding for the intrinsic ID of the item. Assume embedding size 4 for ids and 2 for features, we will have the following vectors:

```
# I use random values for the embeddings
item id = [0,0,0,0]
feature1= [1,1]
feature2= [2,2]
feature3= [3,3]

# You could concat all of this embeddings into a one big item embedding:
item_embedding = [0,0,0,0,1,1,2,2,3,3]
```

The browsing sequence is built by multiple of these `item_embedding` and is what is called `transfomer_features` in the code. 

But transformers dont recognize order within list so we need to provide it explictely, thats where the positional_embedding comes. Here is an explanation:

```
#ie = item_embedding from last example
transfomer_features = [ie1, ie2, ie3, ie4]

# we have a positional embedding table with size=len(transfomer_features ), 4 in this case. We can use the index of each ie1 in the 
# transfomer_features list as the lookup in this embedding and append it to ie.  

# Lets say this our positional embedding table, just 1d embeddings for simplicity
positional_embedding_table= [[0], [1], [2], [3]]

#When we call `transfomer_features = self.positional_embedding(transfomer_features)` we are concatinating the embedding value of the index for each ie with its vector, giving now some information about the position.
transfomer_features = [[0]+ie1,[1]+ ie2, [2]+ie3, [3]+ie4]

```

I think the embedding table is working as expected, we are first building each item embedding by a collection of its features and then concatenating its positional embedding value.

**Comment by shamanez** [comment]
```
     def forward(self, x):
        batch_size = x.size(0)
        return self.pe.weight.unsqueeze(0).repeat(batch_size, 1, 1)

```

Thanks a lot for the detailed explanation. But you can see in the self. positional_embedding function, there's no additional happening to the input features.

**Comment by shamanez** [comment]
Since positional embeddings do not get added to the already encoded features, your transform-encoder layer only processed positional encodings. 

 ```
   def forward(self, batch):
        transfomer_features, user_features, target_movie_rating = self.encode_input(batch)
        **transfomer_features = self.positional_embedding(transfomer_features)
        transformer_output = self.transfomerlayer(transfomer_features)**
```

**Comment by jiwidi** [comment]
> ```
>      def forward(self, x):
>         batch_size = x.size(0)
>         return self.pe.weight.unsqueeze(0).repeat(batch_size, 1, 1)
> ```
> 
> Thanks a lot for the detailed explanation. But you can see in the self. positional_embedding function, there's no additional happening to the input features.

oh yeah! I dont know why i thought i was adding the feature embeddings to the return in that forward. It should be changed to this:

```
transfomer_features = torch.concat(transfomer_features , positional_embedding(transfomer_features)) # Concat the position
```

Good catch! And very important! I'll change it, thanks you!

**Comment by shamanez** [comment]
exactly.  


One more openion, I might be wrong ,

**encoded_sequence_movies_with_poistion_and_rating = (movie_history + positions)**

I think you do not need position embeddings separately. Look at the paper figure (blue color), they just use the usual positional encoding. Actually, anyways you are adding positional encoding later, which is enough for the transformer.

**Comment by jiwidi** [comment]
> encoded_sequence_movies_with_poistion_and_rating

No is right, i had a duplicate positional embedding. I have updated it now with only 1 and doing it outside the encode_input

**Comment by jiwidi** [comment]
ill close this issue, open again if you find any other bugs! thanks

**Comment by shamanez** [comment]
> > encoded_sequence_movies_with_poistion_and_rating
> 
> No is right, i had a duplicate positional embedding. I have updated it now with only 1 and doing it outside the encode_input



> > encoded_sequence_movies_with_poistion_and_rating
> 
> No is right, i had a duplicate positional embedding. I have updated it now with only 1 and doing it outside the encode_input

Perfect.
